### ISSUE TITLE
Cannot submit solution

### ISSUE THREAD

**Issue by sanjarcode** [RudreshVeerkhare/Catalyst#1]
I'm not able to submit solution. Running, adding test cases works fine though.
All requirements are satisified and the keyring is present. I'm on Ubuntu 18.04.
I've tried both C++ and Python, so it's not language specific.

**Comment by RudreshVeerkhare** [comment]
Could you please share more details about the error...
Like what exact message you are getting and all..

**Comment by RudreshVeerkhare** [comment]
submit option working correctly now...
