### ISSUE TITLE
Less than / Greater than symbols don't show up

### ISSUE THREAD

**Issue by kenjpg** [RudreshVeerkhare/Catalyst#12]
Hi,

This might just be an issue on my system but when I load this problem https://codeforces.com/problemset/problem/1304/D into Catalyst, the '<' and '>' symbols are being replaced by &amp;lt; and &amp;gt; respectively.

**Comment by RudreshVeerkhare** [comment]
Thanks @kenjpg  for reporting this issue...😄
There is no problem in your system, it's happening on my PC also...😅
I'll fix it ASAP⚡⚡...

**Comment by RudreshVeerkhare** [comment]
I've fixed this issue in version 1.2.2...🛠
now if you load that problem again, it'll show proper symbols....

Let me know if you face any issues...😄
