### ISSUE TITLE
Less than / Greater than symbols not fully fixed

### ISSUE THREAD

**Issue by kenjpg** [RudreshVeerkhare/Catalyst#13]
Hi, when you open this problem up, https://codeforces.com/problemset/problem/1304/D the symbols display correctly. However, when I clicked the "run all" button to run the testcases, it output my results but also converted the input back to the &amp; symbols. In addition, there seems to be a "space" character of "newline" character at the end? When I took input as string, the last character of string had a space/newline character in it. Sorry if I jumbled my explanation up.

**Comment by RudreshVeerkhare** [comment]
Could you please attach a screenshot of your output....
It'll be more clear that way...

Also try deleting problem data file for this problem from **.catalyst** folder, and then load the problem and try it again...
this might solve the problem....

**Comment by RudreshVeerkhare** [comment]
I got the problem... 
In last commit I fixed it in backend... and forgot to fix the same part in frontend...😅😅
I fixed it now..🔧🛠

And Thank you for reporting this issue...😄
If you still have any issues, feel free to report them....
