### ISSUE TITLE
Test cases that have multiple lines are copied in single line only.

### ISSUE THREAD

**Issue by hm-16** [RudreshVeerkhare/Catalyst#14]
For example,
Input: 3 5
           1 2 3 4
then it copies as : 3 51 2 3 4

**Comment by RudreshVeerkhare** [comment]
Thanks for reporting this issue...  
Could you give problem URL for which this problem is occurring..

**Comment by hm-16** [comment]
For any problem which contains multiple line of inputs .Example

https://codeforces.com/problemset/problem/41/A

In this problem,
Input: code
           edoc
copied input: codeedoc

**Comment by RudreshVeerkhare** [comment]
I've fixed this issus in version 1.3.3..🛠  
Thanks for reporting this ....😄

Let me know if you face any issues...

**Comment by hm-16** [comment]
Thanks a lot .
Today is my first contest at 8:00pm(IST) and you fixed it in time.🙏😁

**Comment by RudreshVeerkhare** [comment]
Oh great !!
Glad to be of help..😁  
All the best for contest... 👍👍 

And do let me no if there are any other issues with Catalyst...

**Comment by hm-16** [comment]
Thanks, I will.
