### ISSUE TITLE
Generated Java file name is not valid

### ISSUE THREAD

**Issue by tausiq** [RudreshVeerkhare/Catalyst#16]
A sample java file generated by this plugins is following, 
`A. Watermelon.java`

This is not a valid java file name. A java solution must have a public class and any public class in a file has to match with the file name. `A. Watermelon` is not a valid class name and not a valid java file name. 

Generating file name requires sanitization, at least for java. 

Thanks!

**Comment by RudreshVeerkhare** [comment]
I have considered this while designing Catalyst...  
You don't need to worry about public class name while using Catalyst...  
You can give **any name** to your public class and Catalyst will take care of it.. 
By take care, I mean when you run your program using Catalyst, it'll execute without any problem...

Important thing is, you must have a public class in the file (It's required for CodeForces) and you can give any name to your public class..  


Hope this clears your doubt...😄

**Comment by tausiq** [comment]
Thanks for your reply. 

I get the point. But what if I would like to debug in VSCode itself? I can't execute (run/debug) without resolving the syntax error. 

What is your rationale to generate file name in this format? 

I think it would be more helpful if the generated file follows this format: `A_Watermelon.java` 

In the source code itself the following template can be used, 

```
public class A_Watermelon {
    pubilc static void main (String[] args) {

    }
} 
```
What's your thought on this?

**Comment by RudreshVeerkhare** [comment]
Yeah, you're right....🤓🧐
It'd much easier to debug using VSCode rather than manual debugging.....😅  

Thanks for pointing out this use case...  😄😁
I'll change It to sanitize filenames... 🛠🔧

**Comment by RudreshVeerkhare** [comment]
Sorry for delay...😔
I've changed the sanitize method...🛠
Now only alpha numeric characters will be in filename....

Let me know if any problem occurs...
