### ISSUE TITLE
Please add support with codeforces.ml

### ISSUE THREAD

**Issue by tw-luo** [RudreshVeerkhare/Catalyst#17]
Because of the bad network, many Chinese users often can't get on the codeforces main site. We often use codeforces.ml (unofficial mirror) to codeforces

**Comment by RudreshVeerkhare** [comment]
Thanks for pointing this out....😃   
In few days, I'll add an option in settings to change this...

**Comment by tw-luo** [comment]
Thanks

**Comment by RudreshVeerkhare** [comment]
I've added option in settings to change default hostname of CodeForces... 😀 
Now you can use `codeforces.ml` as a hostname and it'd work.....  

I've tested some basic things only...🛠🔧
So if there are any issues and bugs, please let me know...😁
