### ISSUE TITLE
[BUG] Input box contents are not displayed properly 

### ISSUE THREAD

**Issue by lampardnk** [RudreshVeerkhare/Catalyst#24]
<img width="533" alt="image" src="https://user-images.githubusercontent.com/28803484/199024359-e8d2551f-0abe-4e46-973b-0856e448b912.png">

This is problem C2 (https://codeforces.com/contest/1732) when opened using URL of contest.

**Comment by RudreshVeerkhare** [comment]
Thanks @lampardnk for raising the issue, I'll look into this ASAP..

**Comment by lampardnk** [comment]
The bug appears to affect only recent contests because the format of the input is different, for https://codeforces.com/contest/14, a very old contest, the extension works fine: 
![image](https://user-images.githubusercontent.com/28803484/201615751-44f80f64-d321-4ac4-baae-967d14de0ac5.png)
