### ISSUE TITLE
Template Loading

### ISSUE THREAD

**Issue by alemanjosh7** [RudreshVeerkhare/Catalyst#7]
I saved the template configuration but later when I started a problem and I opened again my file, it doesn't load the template

**Comment by alemanjosh7** [comment]
Hi, i have a trouble with the directions, actually I'm in a carpet root that I have all my solutions and files of contests but if I want to open a new problem i cannot open in the file named "Contest Number" instead it is saved in the root carpet

**Comment by RudreshVeerkhare** [comment]
Regarding file directory...
Catalyst creates problem file inside of the current workspace..

**Comment by RudreshVeerkhare** [comment]
And for template loading problem could you give some more details please...?
