### ISSUE TITLE
Error when comparing expected output vs program output

### ISSUE THREAD

**Issue by kenjpg** [RudreshVeerkhare/Catalyst#8]
If you put spaces at the end of expected output lines, it does not correctly compare it against program output. 
![Capture](https://user-images.githubusercontent.com/76101897/107018369-bdca2e80-67ce-11eb-9aa2-97bd6aeb8c4a.PNG)
For example, I've put spaces in the underlined area and when comparing against program output it shows it is incorrect. The expected output is generated with 1 space at the end of each line so the error occurs regardless of whether or not I edit it.

**Comment by RudreshVeerkhare** [comment]
Thanks for reporting this issue...
This is fixed in version 0.0.10..
It was just due to extra spaces before newlines..
I've modified RE for that...
